--CREATE DATABASE MeowTest;
USE MeowTest;



CREATE TABLE Roles (
    ID INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	Name VARCHAR(255)
);

CREATE TABLE Users (
	ID INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	Username VARCHAR(20),
	Hashed_password VARCHAR(20),
	Email VARCHAR(100),
	Role_ID INT FOREIGN KEY REFERENCES Roles(ID)
);

CREATE TABLE Assignments (
	ID INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	Img_URL NVARCHAR(255),
	Name VARCHAR(255),
	Description VARCHAR(255),
	User_ID INT FOREIGN KEY REFERENCES Users(ID)
);

CREATE TABLE Categories (
	ID INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	Name VARCHAR(255)
);
CREATE TABLE AssignmentCategories (
	ID INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	Category_ID INT FOREIGN KEY REFERENCES Categories(ID),
	Assignment_ID INT FOREIGN KEY REFERENCES Assignments(ID)
);

CREATE DATABASE OpslagsDatabase